ProjectSocialMedia/ProjectSocialMedia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('SocialMedia/',include('SocialMedia.urls', namespace='SocialMedia')),
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectSocialMedia/SocialMedia/urls.py
from django.urls import path
from . import views

app_name = "SocialMedia"

urlpatterns = [
    # url home page
    path('index/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('blog/', views.blog, name='blog'),
    path('post/<int:id>/', views.post_details, name='post_details'),
    path('contact/', views.contact, name='contact'),
    # Url registration
    path('login/', views.special, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    # url profile user
    path('profiles/', views.profile_list, name='profile_list'),
    path('profiles/<int:pk>/', views.user_profile, name='user_profile'),
    path('profiles/update/<int:user_id>/', views.profile_update, name='profile_update'),
    path('profiles/delete/<int:user_id>/', views.profile_delete, name='profile_delete'),
    path('create_personal_post/', views.create_personal_post, name='create_personal_post'),
    path('personal_post/<int:pk>/edit/', views.edit_personal_post, name='edit_personal_post'),
    path('personal_post/<int:pk>/delete/', views.delete_personal_post, name='delete_personal_post'),
    # url reset password with OTP
    path('send_otp/', views.send_otp, name='send_otp'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('reset_password/<int:user_id>/', views.reset_password, name='reset_password'),
    path('change_password/', views.change_password, name='change_password'),
    # url Social Page,Post
    path('likes/', views.like_list, name='like_list'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('post/<int:post_id>/react/', views.react_to_post, name='react_to_post'),
    path('page/<int:page_id>/like/', views.like_page, name='like_page'),
    path('pages/<int:page_id>/', views.page_detail, name='page_detail'),
    path('pages/manage/', views.manage_page, name='manage_page'), 
    path('pages/manage/<int:page_id>/', views.manage_page, name='manage_page'), 
    path('pages/<int:page_id>/posts/manage/', views.manage_post, name='manage_post'),
    path('posts/manage/<int:post_id>/', views.manage_post, name='manage_post_edit'),   
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('share/<int:post_id>/', views.share_post, name='new_share'), 
    path('share/<int:share_id>/<int:post_id>/', views.share_post, name='share_post'),
    path('comment/<int:comment_id>/delete/', views.delete_post_comment, name='delete_post_comment'),
    path('comment/<int:comment_id>/edit/', views.edit_post_comment, name='edit_post_comment'),
    path('comment/<int:comment_id>/reply/', views.reply_post_comment, name='reply_post_comment'),
    path('group_comment/<int:comment_id>/delete/', views.delete_group_comment, name='delete_group_comment'),
    path('group_comment/<int:comment_id>/edit/', views.edit_group_comment, name='edit_group_comment'),
    path('group_comment/<int:comment_id>/reply/', views.reply_group_comment, name='reply_group_comment'),
    path('group/<int:group_id>/members/', views.manage_group_members, name='manage_group_members'),
    # url friend
    path('friends_list/', views.friends_list, name='friends_list'),
    path('get_friend_list/', views.get_friend_list, name='get_friend_list'),
    path('search-friends/', views.search_friends, name='search_friends'),
    path('send_friend_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('decline_friend_request/<int:request_id>/', views.decline_friend_request, name='decline_friend_request'),
    path('unfriend/<int:friend_id>/', views.unfriend, name='unfriend'),
    path('friends_list/block_friend/<int:friend_id>/', views.blockfriend, name='block_friend'),
    path('block_list/', views.block_list, name='block_list'),
    path('block_list/unblock/<int:user_id>/', views.unblock, name='unblock'),
    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),
    path('notifications/', views.notification_view, name='notifications'),
    path('notifications/read/<int:notification_id>/', views.mark_as_read, name='mark_as_read'),
    # url group
    path('groups/', views.group_list, name='group_list'),
    path('groups/create/', views.create_group, name='create_group'),
    path('groups/update/<int:pk>/', views.update_group, name='update_group'),
    path('groups/delete/<int:pk>/', views.delete_group, name='delete_group'),
    path('groups/<int:pk>/', views.group_detail, name='group_detail'),
    path('groups/<int:pk>/join/', views.join_group, name='join_group'),
    path('groups/<int:group_id>/create_group_post/', views.create_group_post, name='create_group_post'),
    path('posts/<int:post_id>/approve/', views.approve_group_post, name='approve_group_post'),
    path('posts/<int:post_id>/reject/', views.reject_group_post, name='reject_group_post'),
    path('posts/<int:post_id>/edit/', views.edit_group_post, name='edit_group_post'),
    path('posts/<int:post_id>/delete/', views.delete_group_post, name='delete_group_post'),
    path('group/<int:pk>/approve/', views.approve_join_request, name='approve_join_request'),
    path('group/<int:pk>/reject/', views.reject_join_request, name='reject_join_request'),
    path('group/<int:group_id>/leave/', views.leave_group, name='leave_group'),
    path('group/<int:group_id>/reject_join_request/<int:pk>/', views.reject_join_request, name='reject_join_request'),
    # url massages
    path('chat/<int:receiver_id>/', views.chat_view, name='chat_view'),
    path('delete_message/<int:message_id>/', views.delete_message_view, name='delete_message'),
    # like comments
    path('like_comment/<int:comment_id>/', views.like_comment, name='like_comment'),
    # url OnlyFan
    path('create-paid-content/', views.manage_paid_content, name='create_paid_content'),
    path('edit-paid-content/<int:content_id>/', views.manage_paid_content, name='edit_paid_content'),
    path('content/<int:content_id>/purchase/', views.purchase_content, name='purchase_content'),
]

ProjectSocialMedia/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <meta name="csrf-token" content="{{ csrf_token }}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Only Fan Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flex-slider.css' %}">
  </head>

  <body>
  <!-- Header -->
  <header>
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href="{% url 'SocialMedia:index' %}"><h2>Only Fan<em>.</em></h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'SocialMedia:search_friends' %}">
                <i class="fa-solid fa-magnifying-glass"></i>
              </a>
            </li>
            {% endif %}
            <!-- Home link -->
            {% url 'SocialMedia:index' as index_url %}
            <li class="nav-item {% if request.path == index_url %}active{% endif %}">
              <a class="nav-link" href="{{ index_url }}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <!-- Group link -->
            {% url 'SocialMedia:group_list' as group_list_url %}
            <li class="nav-item {% if request.path == group_list_url %}active{% endif %}">
              <a class="nav-link" href="{{ group_list_url }}">Group</a>
            </li>
            <!-- Group Only Fan -->
            {% url 'SocialMedia:about' as about_url %}
            <li class="nav-item {% if request.path == about_url %}active{% endif %}">
              <a class="nav-link" href="{{ about_url }}">Only Fan</a>
            </li>
            <!-- Blog Entries link -->
            {% url 'SocialMedia:blog' as blog_url %}
            <li class="nav-item {% if request.path == blog_url %}active{% endif %}">
              <a class="nav-link" href="{{ blog_url }}">Blog Entries</a>
            </li>
            <!-- Contact Us link -->
            {% url 'SocialMedia:contact' as contact_url %}
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
              <a class="nav-link" href="{{ contact_url }}">Contact Us</a>
            </li>
            <!-- User Profile and Logout for authenticated users -->
            {% if user.is_authenticated %}
            {% url 'SocialMedia:user_profile' user.userprofileinfo.id as user_profile_url %}
            <li class="nav-item {% if request.path == user_profile_url %}active{% endif %}">
              <a class="nav-link" href="{{ user_profile_url }}">
                {% if user.is_staff %}
                Admin: {{ user.username }}
                {% else %}
                User: {{ user.username }}
                {% endif %}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'SocialMedia:notifications' %}">
                <i class="fa-solid fa-bell" style="font-size: 25px;"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'SocialMedia:logout' %}">Logout</a>
            </li>
            {% else %}
            <!-- Guest and Login for unauthenticated users -->
            <li class="nav-item">
              <a class="nav-link" href="#">Guest</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'SocialMedia:user_login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
      
  <!-- content -->
  <main>
    {% block body_block %}
    {% endblock %}
  </main>
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="social-icons">
            <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i> Facebook</a></li>
            <li><a href="#" target="_blank"><i class="fab fa-twitter"></i> Twitter</a></li>
            <li><a href="#" target="_blank"><i class="fab fa-behance"></i> Behance</a></li>
            <li><a href="#" target="_blank"><i class="fab fa-linkedin-in"></i> Linkedin</a></li>
            <li><a href="#" target="_blank"><i class="fab fa-dribbble"></i> Dribbble</a></li>
          </ul>
        </div>
        <div class="col-lg-12">
          <div class="copyright-text">
            <p>Copyright 2024 Stand Blog Co.
              | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">Stolen By Group 3</a></p>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Additional Scripts -->
  <link rel="stylesheet" href="{% static 'assets/js/custom.js' %}">
  <link rel="stylesheet" href="{% static 'assets/js/owl.js' %}">
  <link rel="stylesheet" href="{% static 'assets/js/slick.js' %}">
  <link rel="stylesheet" href="{% static 'assets/js/isotope.js' %}">
  <link rel="stylesheet" href="{% static 'assets/js/accordions.js' %}">

  <script language="text/Javascript"> 
    cleared[0] = cleared[1] = cleared[2] = 0; 
    function clearField(t) {                   
      if (!cleared[t.id]) {                      
        cleared[t.id] = 1;
        t.value = '';         
        t.style.color = '#fff';
      }
    }
  </script>
  <script>
    function toggleSearchBar() {
      const searchBar = document.getElementById('search-bar');
      if (searchBar.style.display === 'none' || searchBar.style.display === '') {
        searchBar.style.display = 'block';
      } else {
        searchBar.style.display = 'none';
      }
    }
  </script>
  {% block script %}
  <script>
                   
  </script>
  {% endblock %}
</body>
</html>